<?php

/**
 * Default button texts.
 */
define('WEBFORM_STRIPE_CONTINUE_TEXT', t('Continue to payment >'));
define('WEBFORM_STRIPE_PAY_TEXT', t('Pay with Stripe'));
define('WEBFORM_STRIPE_CANCEL_TEXT', t('< Return to form'));

/**
 * Implements hook_permission().
 */
function webform_stripe_permission() {
  return array(
    'administer webform stripe' => array(
      'title' => t('Administer Webform Stripe settings'),
      'description' => t('Grants access to change global Stripe Checkout credentials and settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function webform_stripe_menu() {
  $items['admin/config/services/webform-stripe'] = array(
    'title' => 'Webform Stripe',
    'description' => 'Configure Stripe API for Webform.',
    'access arguments' => array('administer webform stripe'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_stripe_settings_form'),
    'file' => 'webform_stripe.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_webform_component_info().
 */
function webform_stripe_webform_component_info() {
  $components['webform_stripe'] = array(
    'label' => t('Stripe payment'),
    'description' => t('Displays a payment button which opens the Stripe Checkout form.'),
    'features' => array(
      'analysis' => FALSE,
      'conditional' => FALSE,
      'default_value' => FALSE,
      'email' => FALSE,
      'description' => FALSE,
      'required' => FALSE,
      'private' => FALSE,
      'title_display' => FALSE,
      'css_classes' => FALSE,
    ),
    'file' => 'webform_stripe.webform.inc',
  );
  return $components;
}

/**
 * Implements hook_libraries_info().
 */
function webform_stripe_libraries_info() {
  return array(
    'stripe-php' => array(
      'name' => 'Stripe API Client Library for PHP',
      'vendor url' => 'https://stripe.com',
      'download url' => 'https://github.com/stripe/stripe-php',
      'version arguments' => array(
        'file' => 'VERSION',
        'pattern' => '/(\d+\.\d+\.\d+)/',
      ),
      'files' => array(
        'php' => array(
          'init.php',
        ),
      ),
    ),
  );
}

/**
 * Loads Stripe PHP library.
 */
function webform_stripe_load_library() {
  $libraries = libraries_get_libraries();

  // If library exists at 'stripe' and is defined by another module (such as
  // Ubercart Stripe), use it to avoid conflicts with loading multiple Stripe
  // PHP libraries.
  if (isset($libraries['stripe'])) {
    $library = libraries_load('stripe');
    if ($library['loaded']) {
      return $library;
    }
  }

  return libraries_load('stripe-php');
}

/**
 * Implements hook_image_default_styles().
 */
function webform_stripe_image_default_styles() {
  $styles['webform_stripe'] = array(
    'label' => 'Webform Stripe',
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 128,
          'height' => 128,
        ),
        'weight' => 1,
      ),
    ),
  );
  return $styles;
}

/**
 * Returns Stripe Checkout settings.
 */
function webform_stripe_checkout_settings() {
  // Merge variable settings with default settings.
  return variable_get('webform_stripe_checkout_settings', array()) + array(
    'name' => variable_get('site_name', 'Drupal'),
    'image' => '',
    'currency' => 'USD',
    'locale' => 'auto',
    'zip-code' => FALSE,
    'billing-address' => FALSE,
    'shipping-address' => FALSE,
    'allow-remember-me' => FALSE,
    'bitcoin' => FALSE,
    'alipay' => FALSE,
    'alipay-reusable' => FALSE,
  );
}

/**
 * Implements hook_form_FORM_ID_alter() for "webform_component_edit_form".
 */
function webform_stripe_form_webform_component_edit_form_alter(&$form, &$form_state) {
  // Alter the Stripe payment component edit form, since Webform doesn't pass
  // the form state to _webform_edit_webform_stripe().
  if ($form['type']['#value'] === 'webform_stripe') {
    form_load_include($form_state, 'inc', 'webform_stripe', 'webform_stripe.webform');
    _webform_edit_webform_stripe_alter($form, $form_state);
  }

  // When editing a Select component that's being used as the dynamic amount or
  // description component, show a reminder message.
  if ($form['type']['#value'] === 'select' && !empty($form_state['build_info']['args'][1]['cid'])) {
    foreach ($form['#node']->webform['components'] as $cid => $component) {
      if ($component['type'] === 'webform_stripe') {
        foreach (array('amount', 'description') as $setting) {
          foreach (array('value', 'plan') as $type) {
            if (
              $component['extra']["{$setting}_type"] === "{$type}_component"
              && isset($component['extra']["{$setting}_{$type}_component"])
              && $component['extra']["{$setting}_{$type}_component"] === $form_state['build_info']['args'][1]['cid']
            ) {
              drupal_set_message(t('The Stripe payment component is using this field to populate the %setting. If you add options to this field, be sure to also update the Stripe payment options.', array(
                '%setting' => $setting,
              )), 'warning');
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for "webform_client_form".
 */
function webform_stripe_form_webform_client_form_alter(&$form, &$form_state, $form_id) {
  form_load_include($form_state, 'inc', 'webform_stripe', 'webform_stripe.webform');
  _webform_stripe_form_webform_client_form_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter() for "webform_configure_form".
 */
function webform_stripe_form_webform_configure_form_alter(&$form, &$form_state) {
  // If form has Stripe payment component, disable the Submit button label
  // field and let the user know why.
  foreach ($form['#node']->webform['components'] as $component) {
    if ($component['type'] === 'webform_stripe') {
      $form['advanced']['submit_text']['#disabled'] = TRUE;
      $form['advanced']['submit_text']['#description'] = t('This form has a Stripe payment component, which changes the way the Submit button works, so this field has no effect and has been disabled.');
    }
  }
}
